# site settings

title: thunderfurri
description: A dumb gamedev
taglong: A dumb gamedev
tagshort: dumbass
url: https://thunderfurry.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/thunderfurry/thunderfurry.github.io

# author settings

author:
  name: Place Holder
  email: username@domain.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
